name: plome_deploy_infomaniak

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    steps:
      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
      
